#! /usr/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# This is a (wrapper) script to update the bootloader config.
#
# It checks /etc/sysconfig/bootloader for the bootloader type.
#
# If there's no bootloader configured, it does nothing.
#
# If the directory /usr/lib/bootloader/$LOADER exists, runs the scripts from
# that directory.
#
# For any other bootloader it runs the old bootloader_entry and
# update-bootloader scripts (renamed to *.old).
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

VERSION="0.0"

pbl_dir="/usr/lib/bootloader"
exit_code=0

opt_log="/var/log/pbl.log"


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# bl_usage $exit_code
#
# Print help text and exit.
#
bl_usage () {
  cat <<EOF
Usage: pbl [OPTIONS]
Configure/install boot loader.

Options:
    --install                   Install boot loader.
    --config                    Create boot loader config.
    --show                      Print current boot loader.
    --loader BOOTLOADER         Set current boot loader to BOOTLOADER.
    --default ENTRY             Set default boot entry to ENTRY.
    --add-option OPTION         Add OPTION to default boot options (grub2).
    --del-option OPTION         Delete OPTION from default boot options (grub2).
    --get-option OPTION         Get OPTION from default boot options (grub2).
    --add-kernel VERSION [KERNEL [INITRD]]
                                Add kernel with version VERSION. Optionally pass kernel and initrd
                                explicitly (systemd-boot).
    --remove-kernel VERSION [KERNEL [INITRD]]
                                Remove kernel with version VERSION. Optionally pass kernel and initrd
                                explicitly (systemd-boot).
    --log LOGFILE               Log messages to LOGFILE (default: /var/log/pbl.log)
    --version                   Show pbl version.
    --help                      Write this help text.

EOF

  exit $1
}


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
while true ; do
  case $1 in
    --install) opt_install=1 ; shift ; continue ;;
    --config) opt_config=1 ; shift ; continue ;;
    --show) opt_show=1 ; shift ; continue ;;
    --log) opt_log="$2" ; shift 2 ; continue ;;
    --version) echo $VERSION ; exit 0 ;;
    -h|--help) bl_usage 0 ;;
  esac

  break
done



bl_usage 2

exit $exit_code
