#! /usr/bin/sh

# Settings from /etc/sysconfig/filename are available as environment vars
# with the name 'SYS__FILENAME__KEY' (filename converted to upper case).
#
# Not all files are parsed, current list is:
#   bootloader, language
#

# include common functions
. "$PBL_INCLUDE/library"

lib_get_cmdline_bls

err=0
if [ -x /usr/bin/bootctl ]; then
  kernel=$(bootctl status | grep linux: | cut -d':' -f2 | tr -d ' ')
  initrd=$(bootctl status | grep initrd: | cut -d':' -f2 | tr -d ' ')
  append=\"$(lib_shellquote "$cmdline")\"

  echo "kernel=$kernel" > "$PBL_RESULT"
  echo "initrd=$initrd" >> "$PBL_RESULT"
  echo -n "append=$append" >> "$PBL_RESULT"
else
  echo "bootctl: command not found"
  err=1
fi

exit $err
