#! /usr/bin/sh

# Settings from /etc/sysconfig/filename are available as environment vars
# with the name 'SYS__FILENAME__KEY' (filename converted to upper case).
#
# Not all files are parsed, current list is:
#   bootloader, language
#

# usage: del-option OPTION
#
# Delete default boot option.
#
# OPTION is either of the form 'key=value' or 'key="value"' or just 'key'.

# include common functions
. "$PBL_INCLUDE/library"

opt="$1"

lib_get_cmdline_bls

echo "cmdline (old): $cmdline"

lib_del_option "$opt"

if [ -z "$changed" ] ; then
  echo "cmdline not updated"
  exit 0
fi

echo "cmdline (new): $cmdline"

lib_set_cmdline_bls

exit 0
