#! /usr/bin/sh

# Settings from /etc/sysconfig/filename are available as environment vars
# with the name 'SYS__FILENAME__KEY' (filename converted to upper case).
#
# Not all files are parsed, current list is:
#   bootloader, language
#

err=0
if [ -x /usr/bin/sdbootutil ] ; then
  sdbootutil install || err=1
else
  echo "sdbootutil: command not found"
  err=1
fi

exit $err
