#! /usr/bin/bash

# Settings from /etc/sysconfig/filename are available as environment vars
# with the name 'SYS__FILENAME__KEY' (filename converted to upper case).
#
# Not all files are parsed, current list is:
#   bootloader, language
#

# usage: remove-kernel KERNEL-VERSION
#
# Remove kernel/initrd from boot config.

# include common functions
. "$PBL_INCLUDE/library"

err=0
if [ -x /usr/bin/kernel-install ] ; then
  ( set -x ; kernel-install remove "$1" ) || err=1
else
  echo "kernel-install: command not found"
  err=1
fi

exit $err
