#! /usr/bin/bash

# Settings from /etc/sysconfig/filename are available as environment vars
# with the name 'SYS__FILENAME__KEY' (filename converted to upper case).
#
# Not all files are parsed, current list is:
#   bootloader, language
#

# include common functions
. "$PBL_INCLUDE/library"

target=$(uname -m)

case "$target" in
  x86_64|i?86)
    image=vmlinuz ;;
  ppc*)
    image=vmlinux ;;
  s390*)
    image=image ;;
  armv*)
    image=zImage ;;
  aarch64|riscv64)
    image=Image ;;
  *)
    echo "Architecture $target not supported."
esac

lib_get_cmdline_grub

lib_get_default_kernel_initrd

append=\"$(lib_shellquote "$cmdline")\"

echo "kernel=$default_kernel" > "$PBL_RESULT"
echo "initrd=$default_initrd" >> "$PBL_RESULT"
echo -n "append=$append" >> "$PBL_RESULT"

exit 0
