#! /bin/bash

target=$(uname --hardware-platform)

if [ -z "$target" ] ; then
  echo "no target platform"
  exit 1
fi

case "$target" in
  i?86 | x86_64 ) target=i386-pc ;;
  ppc | ppc64 ) target=powerpc-ieee1275 ;;
  s390x ) target=s390x-emu ;;
esac

echo "target = $target"

if [ -x /usr/sbin/grub2-install ] ; then
  if [ -f /etc/default/grub_installdevice ] ; then
    while read foo ; do
      [ -z "$foo" -o "$foo" = activate -o "$foo" = generic_mbr ] && continue
      if [ -b "$foo" ] ; then
        ( set -x ; /usr/sbin/grub2-install --target="$target" --force --skip-fs-probe "$foo" ) || exit
      else
        echo "$foo: not a block device"
        exit 1
      fi
    done </etc/default/grub_installdevice
  else
    echo "/etc/default/grub_installdevice: no such file"
    exit 1
  fi
else
  echo "grub2-install: command not found"
  exit 1
fi

